version: '3'

services:
  postgres:
    image: 'postgres:9.5'
    environment:
      POSTGRES_USER: 'upali'
      POSTGRES_PASSWORD: 'yourpassword'
      #    ports:
      #      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server --requirepass yourpassword
    expose:
      - '6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  website:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    ports:
      - "3000:3000"
    volumes:
      - '.:/upali'
      - 'assets-volume:/upali/public/assets'
    env_file:
      - '.env'

  sidekiq:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: sidekiq -C config/sidekiq.yml.erb
    volumes:
      - '.:/upali'
    env_file:
      - '.env'

  cable:
    depends_on:
      - 'redis'
    build: .
    command: puma -p 28080 cable/config.ru
    expose:
      - '28080'
    volumes:
      - '.:/upali'
    env_file:
      - '.env'

  nginx:
    depends_on:
      - 'website'
    image: 'nginx'
    command: /bin/bash -c "cat < /etc/nginx/conf.d/upali.site > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    volumes:
      - './upali.site:/etc/nginx/conf.d/upali.site'
      - 'assets-volume:/var/www/51upali.com/public/assets'
      - '.:/var/www/51upali.com'
    ports:
      - "80:80"
    restart: 'always'

volumes:
  redis:
  postgres:
  assets-volume:
